FROM node:14-alpine

WORKDIR /app
RUN apk --no-cache --virtual build-dependencies add \
        python3 \
        make \
        g++
ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm install
RUN npm install @vue/cli@3.7.0

CMD ["npm", "run", "serve"]