version: '3.3'

services:
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        ports: 
            - 8081:8080
        restart: always
        environment:
            - VUE_APP_API_BASE_URL=http://localhost:8000
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
    server: 
        build: ./server
        volumes:
            - ./server/app:/app
        ports:
            - "8000:80"
        environment:
            - ENVIRONMENT=dev
            - DATABASE_URL=postgres://user:notasafepassword@db/fastsnippets_db
            - SECRET_KEY=notasecret
        command: /start-reload.sh
        depends_on:
            - db

    db:
        image: postgres:12.0-alpine
        environment:
         - POSTGRES_USER=user
         - POSTGRES_PASSWORD=notasafepassword
         - POSTGRES_DB=fastsnippets_db
         - PGDATA=/tmp
        volumes:
            - app-db-data:/var/lib/postgresql/data/pgdata

    pgadmin:
        image: dpage/pgadmin4
        environment:
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
        - "5050:80"
        depends_on:
        - db

volumes:
    app-db-data:
    
    

    
