version: '3.3'

services:
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        ports: 
            - 8081:8080
        restart: always
        environment:
        - NODE_ENV=development
        - CHOKIDAR_USEPOLLING=true

    server: 
        build: ./server
        volumes:
            - ./server:/usr/src/app
        ports:
            - 8000:80
        environment:
            - ENVIRONMENT=dev
            - DATABASE_URL=postgresql://dami:wildflower@db/snippets
            - SECRET_KEY=notasecret
        depends_on:
            - db
    
    db:
        image: postgres:12.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
         - POSTGRES_USER=dami
         - POSTGRES_PASSWORD=wildflower
         - POSTGRES_DB=snippets

    pgadmin:
        image: dpage/pgadmin4
        environment:
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
        - "5050:80"
        depends_on:
        - db
    
    
volumes:
    postgres_data:
    
