version: '3.3'

services:
    client:
        build: ./client
        volumes:
            - /usr/src/app/node_modules
            - ./client:/usr/src/app
        ports: 
            - 3000:80
        restart: always
        environment:
        - NODE_ENV=development

    server: 
        build: ./server
        volumes:
            - ./server:/usr/src/app
        ports:
            - 8000:80
        environment:
            - ENVIRONMENT=dev
            - DATABASE_URL=postgresql://dami:wildflower@localhost:5432/snippets
        depends_on:
            - db
    
    db:
        image: postgres:12.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_USER=dami
        - POSTGRES_PASSWORD=wildflower
        - POSTGRES_DB=snippets
    
volumes:
    postgres_data:
    
