version: '3.3'

services:
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        ports: 
            - 8081:8080
        restart: always
        environment:
        - NODE_ENV=development
        - CHOKIDAR_USEPOLLING=true

    server: 
        build: ./server
        volumes:
            - ./server/app:/app
        ports:
            - 8000:80
        environment:
            - ENVIRONMENT=dev
            - DATABASE_URL=postgresql://user:notasafepassword@db/snippets_db
            - SECRET_KEY=notasecret
        command: /start-reload.sh
        depends_on:
            - db
    
    db:
        image: postgres:12.0-alpine
        environment:
         - POSTGRES_USER=user
         - POSTGRES_PASSWORD=notasafepassword
         - POSTGRES_DB=snippets_db

    pgadmin:
        image: dpage/pgadmin4
        environment:
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
        - "5050:80"
        depends_on:
        - db
    
    

    
